In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats as sT
import altair as alt

from scipy import stats

In [2]:
covar = pd.read_csv("../data_primary/covarExted.csv").set_index("QBB_DUMMY_ID")
IgE = pd.read_csv("/Users/tkhan/ImmunoGenomics_NM/AllergenAutiAb_IgE_Sep2019/QBBIgE_IU_MR_July182019.csv").loc[:799]
igE_raw = pd.read_csv("../data_primary/clinicIgE_rawData.csv").set_index("QBB_DUMMY_ID")

In [4]:
igE_raw

,fx1,fx2,fx22,fx5,gx2,phad,t20,wx1
QBB_DUMMY_ID,,,,,,,,
SIR000037000780,0.004688,0.030764,0.158547,0.040405,0.061567,0.182508,0.029467,0.142290
SIR000037000142,0.000000,0.070241,0.129783,0.089441,0.063238,0.320504,0.016894,0.205851
SIR000037000275,0.355763,1.596741,0.403655,0.533030,0.283591,1.395833,0.129739,0.503114
SIR000037000009,0.038830,0.000000,0.147813,0.122652,0.094520,0.209529,0.000000,0.155590
SIR000037000702,0.068248,0.000000,0.166260,0.134755,0.073208,1.589408,0.391426,0.457234
...,...,...,...,...,...,...,...,...
SIR000037000061,0.047589,4.065160,0.269296,0.441743,0.240977,3.636251,0.259336,0.986090
SIR000037000281,0.010382,0.044473,0.191027,0.174846,0.213236,0.278512,0.010518,0.231748
SIR000037000282,0.010833,0.000000,0.173047,0.041801,0.081115,0.213718,0.003010,0.157595
SIR000037000063,0.000000,0.033281,0.139403,0.044340,0.043850,0.482163,0.002872,0.148941
SIR000037000062,0.248584,0.000000,0.183180,0.365462,0.057455,0.295186,0.032254,0.178136

In [5]:
igE_gradeing = pd.DataFrame(index=igE_raw.index, columns=igE_raw.columns)
for k in igE_raw.columns:
    g6 = igE_raw[k][igE_raw[k]>=100].index
    igE_gradeing.loc[g6,k] = '6'
    g5 = igE_raw[k][(igE_raw[k]>=52.5)&(igE_raw[k]<100)].index
    igE_gradeing.loc[g5,k] = '5'
    g4 = igE_raw[k][(igE_raw[k]>=17.5)&(igE_raw[k]<52.5)].index
    igE_gradeing.loc[g4,k] = '4'
    g3 = igE_raw[k][(igE_raw[k]>=3.5)&(igE_raw[k]<17.5)].index
    igE_gradeing.loc[g3,k] = '3'
    g2 = igE_raw[k][(igE_raw[k]>=0.7)&(igE_raw[k]<3.5)].index
    igE_gradeing.loc[g2,k] = '2'
    g1 = igE_raw[k][(igE_raw[k]>=0.35)&(igE_raw[k]<0.7)].index
    igE_gradeing.loc[g1,k] = '1'
    g0 = igE_raw[k][igE_raw[k]<0.35].index
    igE_gradeing.loc[g0,k] = '0'

In [10]:
igE_gradeingPV = igE_gradeing.unstack().reset_index().rename({'level_0':'allergy',0:'grading'},axis=1)

In [15]:
igE_gradeingPVCount = igE_gradeingPV.groupby(['allergy','grading']).size().reset_index().rename({0:'sampleCount'},axis=1)
igE_gradeingPVCount['sampleFrac'] = igE_gradeingPVCount.sampleCount/igE_gradeing.shape[0]

In [17]:
igE_gradeingPVCount.pivot_table(index='allergy',columns='grading',values='sampleCount')

grading      0      1      2     3     4    5
allergy
fx1      769.0   11.0   13.0   4.0   NaN  NaN
fx2      649.0   47.0   69.0  28.0   4.0  NaN
fx22     745.0   31.0   16.0   3.0   NaN  NaN
fx5      715.0   50.0   26.0   4.0   NaN  NaN
gx2      706.0   35.0   37.0  14.0   4.0  1.0
phad     444.0  103.0  148.0  73.0  27.0  2.0
t20      725.0   33.0   28.0   8.0   3.0  NaN
wx1      600.0   80.0   88.0  26.0   3.0  NaN

In [21]:
igE_gradeingPV[igE_gradeingPV.grading>='4'].pivot(index='QBB_DUMMY_ID',columns='allergy',values='grading')

allergy          fx2  gx2 phad  t20  wx1
QBB_DUMMY_ID
SIR000037000031  NaN  NaN    4  NaN  NaN
SIR000037000069  NaN    5    5  NaN  NaN
SIR000037000082  NaN    4    4  NaN  NaN
SIR000037000087  NaN  NaN    4  NaN  NaN
SIR000037000104  NaN  NaN    4  NaN  NaN
SIR000037000119  NaN  NaN    4  NaN  NaN
SIR000037000127  NaN  NaN    4  NaN  NaN
SIR000037000139  NaN    4  NaN  NaN  NaN
SIR000037000147  NaN  NaN    5  NaN  NaN
SIR000037000151    4  NaN    4  NaN  NaN
SIR000037000152  NaN  NaN    4  NaN  NaN
SIR000037000198  NaN  NaN    4  NaN  NaN
SIR000037000204  NaN  NaN    4  NaN  NaN
SIR000037000205  NaN  NaN    4  NaN  NaN
SIR000037000244  NaN  NaN    4  NaN  NaN
SIR000037000257  NaN  NaN    4  NaN  NaN
SIR000037000270  NaN  NaN    4  NaN  NaN
SIR000037000306    4  NaN  NaN  NaN  NaN
SIR000037000316  NaN    4    4  NaN  NaN
SIR000037000340  NaN  NaN    4  NaN  NaN
SIR000037000342  NaN    4  NaN  NaN  NaN
SIR000037000350  NaN  NaN  NaN    4    4
SIR000037000445  NaN  NaN    4  NaN  NaN
SIR000037000488  NaN  NaN    4    4  NaN
SIR000037000519  NaN  NaN    4  NaN    4
SIR000037000533  NaN  NaN    4  NaN  NaN
SIR000037000589  NaN  NaN    4    4    4
SIR000037000645  NaN  NaN    4  NaN  NaN
SIR000037000667    4  NaN  NaN  NaN  NaN
SIR000037000692  NaN  NaN    4  NaN  NaN
SIR000037000708    4  NaN    4  NaN  NaN
SIR000037000716  NaN  NaN    4  NaN  NaN
SIR000037000733  NaN  NaN    4  NaN  NaN
SIR000037000787  NaN  NaN    4  NaN  NaN